### ISSUE TITLE
23.09.1-RELEASE (amd64)

### ISSUE THREAD

**Issue by DeFlanko** [LeonStraathof/pfsense-speedtest-widget#2]
pfSense:
23.09.1-RELEASE (amd64)
built on Thu Feb 15 21:44:00 PST 2024
FreeBSD 14.0-CURRENT

The system is on the latest version.
Version information updated at Sat Mar 23 8:16:29 PDT 2024

------------
Issue:
```Log
pkg: Warning: Major OS version upgrade detected.  Running "pkg bootstrap -f" recommended
Fetching ookla-speedtest-1.2.0-freebsd13-x86_64.pkg: .......... done
Installing speedtest-1.2.0.84-1.ea6b6773cf...
pkg: speedtest-1.2.0.84-1.ea6b6773cf conflicts with py38-speedtest-cli-2.1.3 (installs files into the same place).  Problematic file: /usr/local/bin/speedtest

Failed to install the following 1 package(s): https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-freebsd13-x86_64.pkg
```

**Comment by LeonStraathof** [comment]
This is a know issue and a problem between the original speedtest from Ookla and the unofficial implementation that is in the FreeBSD repository. This should be reported to FreeBSD and not here as i can not do anything about this problem. Please uninstall the unofficial version that FreeBSD has in the repository and is not even properly maintained as they are not allowed because of copyrights before installing the official one. `pkg delete -y py38-speedtest-cli-2.1.3`
