### ISSUE TITLE
Speedtest CLI only providing FreeBSD 13 version while pfSense is on FreeBSD 14

### ISSUE THREAD

**Issue by SPYR0999** [LeonStraathof/pfsense-speedtest-widget#5]
Hey thanks for the great work this widget seems amazing!

Before I carry on with my installation, I want to make sure I do things right and I am not 100% familiar with the inner workings of FreeBSD.

On their website, Speedtest CLI only reports having versions for FreeBSD 12 and 13, but when I looked at my pfSense install, it shows I am on FreeBSD 14 (2.7.0-RELEASE).

Is that something that could be an issue and that I should avoid installing? I do not know how FreeBSD manages backwards compatibility for packages and I want to make sure not to break anything.

**Comment by LeonStraathof** [comment]
Hi, yes the latest version that speedtest.net currently has made for is for BDS 13. The installation instructions already accounted for that. As for your question if it will not break BSD, no it will not. Only things that can break is if there is some other software that depends on this particular software. However i do not think there is anything in the OS or in any mainstream that has the speedtest.net software as a dependency. I know that from the BSD repository there is a speedtest, but the problem is actually the other way around that "official" implementation is actually wrong and bad. The "official" version for BSD is actually intentional broken because else they might get into legal problems as it tries to implement something that is not opensource.
